### PR TITLE
submit 2 cases for vol. 2 from summer 2016

### PR DESCRIPTION
**Pull request by garretchristensen**
I collected 2 cases from the BITSS summer folks and Bad Hessian blog
call

### CODE REVIEW

**Comment by danielturek** [comment]
@jkitzes @garretchristensen What is the status of this PR and these two case studies?  (dsinghania, wkrause).

Are these being used in the second volume, the social sciences book?

**Comment by garretchristensen** [comment]
Yes, they're for the second volume, in whatever form that takes. I am definitely not going to get enough case studies for a social science themed volume, so I have abandoned that hope. But as I recall @jkitzes wanted to keep the initial collection going and open to additions in some form, so here you go, we've got two submissions already.

**Comment by danielturek** [comment]
Got it, I wasn't aware of those developments.  @jkitzes is there a better place for these submissions, or just keep the PR open?

**Comment by jkitzes** [comment]
I think for now let's just leave this open. I'm not sure if we should add an Appendix (or something similar) to the existing book or set up a second version of the online book for the new case studies. Might hold off to see if we get any more after this symposium and book launch and use that to decide.

**Comment by danielturek** [comment]
Agreed.  Let's wait until after the symposium, in any case.

**Comment by garretchristensen** [comment]
Just adding a note here so that we don't forget the additional submission from Andrea Seisler and Rick Gilmore.

**Comment by jkitzes** [comment]
Superseded by later commits.

**Pull request closed without merging**
