### PR TITLE
updating figure with bigger fonts

### PR DESCRIPTION
**Pull request by choldgraf**
These are updates to my two figures for readability. @jkitzes lemme know what you think

### CODE REVIEW

**Comment by danielturek** [comment]
@choldgraf One minor suggestion, perhaps make the font size of the parenthetical material in each box slightly smaller?  That would emphasise the main text, and also fit (.hdf, .csv, .svg) on a single line in the Results Folder, which I think would look better.

Any way you can think to make the Viz Formatting text only require 3 lines, also?  Either change Adobe Illustrator to just Illustrator, or perhaps make that box (only) slightly wider?  Thoughts?

**Comment by choldgraf** [comment]
Cool - check the latest commit. I also edited a couple of lines for typos,
formatting, and small changes.
--

**Comment by danielturek** [comment]
@choldgraf Revised diagram looks great.  I'm merging this PR right now, but if you find other things you decide to change, feel free to create another.  Thanks for the quick edits.

**Comment by choldgraf** [comment]
🍻

**Pull request merged**
