### PR TITLE
diagram revisions

### PR DESCRIPTION
**Pull request by danielturek**
@jkitzes @fatmai Submitting a PR with my diagram revisions.  In several cases I ended up remaking the diagram, but I think all of these follow our formatting guidelines quite well.

Includes revisions for the following case study diagrams:

akrause
dturek
khinsen
millmanOttoboniStark
rjleveque
rpoldrack
slaybaugh
tmadhyastha
vstaneva

### CODE REVIEW

**Comment by jkitzes** [comment]
Great, thanks Daniel. For tracking purposes, I'll leave this unmerged for now until all three of us submit revisions. Then I'll check all one final time, printed out, against the font size masters, before merging all.

**Comment by danielturek** [comment]
Sounds good.

I did the print-check myself, too (see [figure-check-v1_DT.pdf](https://github.com/BIDS/repro-case-private/blob/master/figure_checks/figure-check-v1_DT.pdf) in the private repo), but your path forward makes sense.

**Comment by danielturek** [comment]
@jkitzes Are we still waiting to merge this in?

**Comment by jkitzes** [comment]
At one point I thought I'd merge all at once, but don't see any reason to wait at this point. Looks like we've got everything done except aarendt, I think. I'll merge your PR here and mine, and we'll wait for @fatmai to confirm on her end and then merge hers.

**Pull request merged**
