### PR TITLE
cboettig document updated

### PR DESCRIPTION
**Pull request by cboettig**
@jkitzes Okay, took a quick stab at addressing the issues brought up in #43 , including a new diagram.  May still need some iteration, but perhaps we can re-open #43?

### CODE REVIEW

**Comment by jkitzes** [comment]
Thanks Carl, looks like a great start, much more in line with how we're hoping to structure all of the case studies. I can see there are a few things still to do as described in #43, but I'll hand off further comments to @danielturek and @fatmai, who have been closely reading and reviewing all of the case studies. (Looping in @katyhuff also for any comments.)

**Comment by katyhuff** [comment]
bitmoji

**Comment by fatmai** [comment]
I added some comments to #43. This is mostly done just few small things left.

**Comment by danielturek** [comment]
@cboettig Requesting one more modification to your diagram, per most recent comments in #43.

**Pull request merged**
