### PR TITLE
Fi figure rev

### PR DESCRIPTION
**Pull request by fatmai**
This PR includes figure changes for 
fatmai, barbera, chartgerink, dholland, kasmislan, dushizima

Following two only provided xml files but not svg files: omesnard,jgukelberger

aarendt provided pptx file. @jkitzes, @danielturek  any suggestion how to deal with those.

### CODE REVIEW

**Comment by danielturek** [comment]
@fatmai The xml files `omesnard.xml` and `jgukelberger.xml` both opened fine for me using draw.io, so they should be easy to edit there.

`aarendt.pptx` I would just revise in PowerPoint.  I had one like that, as well.

**Comment by fatmai** [comment]
oh right, draw.io. I somehow ignored that. I will check those in draw.io. The one on PowerPoint is tricky as it won't be as accurate as the other ones. I will check. thanks, @danielturek

**Comment by fatmai** [comment]
omenard and jgukelberger added. will redo aarendt.pptx.

**Comment by danielturek** [comment]
@jkitzes @fatmai Same question here -- still waiting to merge this?

**Comment by jkitzes** [comment]
@fatmai, is aarendt the only one missing here? If so I'll merge, and I can clean up that one (I did one other Powerpoint one already and think I could do that one without too much trouble).

(Was holding off on merge originally until we had all of them done here.)

**Comment by fatmai** [comment]
@jkitzes yes. aarendt's is a pptx file which I think I need to remake. It is harder to me to figure out how to adjust in power point ¯\_(ツ)_/¯. If you can adjust it without much trouble and don't need to remake an svg then I would be very happy for the help. If you end up going the remake route, I am happy to take over.

**Comment by danielturek** [comment]
@fatmai I believe you managed to get a Katakana character in your comment!  How's that?  It looks like a "tsu", with some underscores and such surrounding it.

**Comment by danielturek** [comment]
Per discussion of stage names in dholland diagram, leaving this PR to @jkitzes to review and merge.

**Comment by fatmai** [comment]
yes, @jkitzes as mentioned in the email, we need to merge this before the final online book otherwise these figures will have unrevised fonts or stage names. 
Also let me know how it goes with aarendt's figure.

**Comment by jkitzes** [comment]
Ah my bad, this was my to do. I'll resolve the image conflict here and merge.

**Pull request merged**
